<?php
/**
 * Technooze_Treview extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Technooze
 * @package    Technooze_Treview
 * @copyright  Copyright (c) 2008 Technooze LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 *
 * @category Technooze
 * @package  Technooze_Treview
 * @module   Treview
 * @author   Damodar Bashyal (enjoygame @ hotmail.com)
 */
 ?>
 <div class="view-stars">
    <h4>Customer Reviews and Ratings</h4>
    <div class="ratings">
            <div class="rating-box" title="<?php echo $this->getRatingSummary() ?>%">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <br />
        <p class="rating-links">
            <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d review(s)', $this->getReviewsCount()) ?></a> | 
            <a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Write a Review') ?></a>
        </p>
    </div>
</div>
